#!/usr/bin/env python

import rospy

from comp0037_explorer.explorer_node_f import ExplorerNodeF

if __name__ == '__main__':
    try:
        explorerNode = ExplorerNodeF()
        explorerNode.run()
    except rospy.ROSInterruptException:
        pass
